spring:
  datasource:
    master:
      # 配置数据源类型
      type:
        com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化，最小，最大连接数
      initialSize: 3
      minidle: 3
      maxActive: 18
      # 获取数据库连接等待的超时时间
      maxWait: 60000
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM dual
      # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
      filters: stat
    slave:
      jdbc-url: jdbc:sqlserver://192.168.2.155:1433;database=ZujuanMobileSite
      username: zujuan
      password: 21cn.com
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0 # Redis数据库索引（默认为0）
    lettuce:    # 如果使用的jedis 则将lettuce改成jedis即可
      pool:
        max-active: 8   # 最大活跃链接数 默认8
        max-idle: 8     # 最大空闲连接数 默认8
        min-idle: 0     # 最小空闲连接数 默认0
    timeout: 10000
